#!/bin/bash

# CONFIG ########################################################

# Enter your google api key here
api_key="XXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXX-XXXXX"

# Uncomment this to set the download directory
# cd "~/Music/magictube"

# SCRIPT ########################################################

if [ -z "$1" ]
  then
    echo "No query"
    exit
fi

query="'$*'"

video_id=$(curl --silent -G --data-urlencode "key=$api_key" --data-urlencode "maxResults=1" --data-urlencode "q=$query" https://www.googleapis.com/youtube/v3/search | jq '.items[0] .id .videoId')
video_id="${video_id#\"}"

output=$(youtube-dl --no-warnings --get-filename -f 140 -no-part -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=$video_id)

title=${output::-4}

trap "rm '$output.part'; exit 130" INT

echo "Downloading $title"

youtube-dl --no-warnings -f 140 -no-part -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=$video_id &>/dev/null

echo "Enjoy!"

xdg-open "./$output" &>/dev/null
